name: Tinglysning

on:
  workflow_dispatch:

jobs:
  tinglysning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/ESStatistikListeParser-GitHub"
          ref: "main"
          path: "${{ github.workspace }}/"
          sparse-checkout: |
            /go.mod
            /go.sum
            /Tinglysning-GitHub.go
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Install MongoDB
        uses: ankane/setup-mongodb@v1
        with:
          mongodb-version: 8.0

      - name: Create MongoDB database
        run: |
          mongosh --host localhost:27017 <<EOF
            db = db.getSiblingDB('bilgaden');
            db.createCollection('tinglysning');
          EOF

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install Go dependencies
        run: go mod tidy

      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps chromium

      - name: Run Tinglysning Go script
        run: |
          go run Tinglysning-GitHub.go
