name: Tinglysning

on:
  workflow_dispatch:
    inputs:
      remove-count-from-vins:
        description: 'Remove count from vins'
        required: true
        type: string
        default: "0"
      github-upload-limit:
        description: 'GitHub Upload Limit (In MiB)'
        required: true
        type: string
        default: "100"

jobs:
  tinglysning:
    runs-on: ubuntu-latest

    steps:
      - name: Display runner information
        run: |
          echo "cpu-core:       $(nproc --all)"
          echo "cpu-model:      $(grep 'model name' /proc/cpuinfo | head -1 | cut -d: -f2- | sed 's/^[[:space:]]*//')"
          echo "hostname:       $(hostname)"
          echo "kernel-release: $(uname -r)"
          echo "kernel-version: $(uname -v)"
          echo "name:           $(grep '^NAME=' /etc/os-release | head -1 | cut -d= -f2- | tr -d '\"')"
          echo "platform:       $(uname -s)"
          echo "release:        $(grep '^VERSION_ID=' /etc/os-release | head -1 | cut -d= -f2- | tr -d '\"')"
          echo "total-memory:   $(grep MemTotal /proc/meminfo | awk '{print $2 * 1024}')"

      - name: Set environment variables
        run: |
          echo "SHOULD_SPAWN_NEW_RUNNER=false" >> $GITHUB_ENV
          echo "REMOVE_COUNT_FROM_VINS=${{ inputs.remove-count-from-vins }}" >> $GITHUB_ENV

          echo "EXIST_TINGLYSNING_BRANCH=false" >> $GITHUB_ENV
          echo "EXIST_TINGLYSNING_TEMP_BRANCH=false" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/ESStatistikListeParser-GitHub"
          ref: "main"
          path: "${{ github.workspace }}/"
          sparse-checkout: |
            /go.mod
            /go.sum
            /Tinglysning-GitHub.go
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Checkout Bilgaden repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/Bilgaden"
          ref: "main"
          path: "${{ github.workspace }}/temp/"
          sparse-checkout: |
            !/*
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Set up Git
        working-directory: "${{ github.workspace }}/temp/"
        run: |
          gh auth login --with-token <<< "${{ secrets.PAT }}"

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global http.postBuffer 104857600
          
          if git ls-remote --exit-code --heads origin tinglysning; then
              echo "EXIST_TINGLYSNING_BRANCH=true" >> $GITHUB_ENV
          else 
              echo "Branch 'tinglysning' does not exist, creating..."
              
              git switch --orphan tinglysning
              git commit --allow-empty -m "Created Tinglysning branch"
              git push origin tinglysning
          fi

          if git ls-remote --exit-code --heads origin tinglysning-temp; then
              echo "EXIST_TINGLYSNING_TEMP_BRANCH=true" >> $GITHUB_ENV
          else
              echo "Branch 'tinglysning-temp' does not exist, creating..."
              
              git switch --orphan tinglysning-temp
              git commit --allow-empty -m "Created Tinglysning-Temp branch"
              git push origin tinglysning-temp
          fi

          rm -rf ${{ github.workspace }}/temp/

      - name: Checkout Bilgaden repository (Tinglysning-branch)
        if: ${{ (env.EXIST_TINGLYSNING_BRANCH == 'false' && env.EXIST_TINGLYSNING_TEMP_BRANCH == 'false') || (env.EXIST_TINGLYSNING_BRANCH == 'true' && env.EXIST_TINGLYSNING_TEMP_BRANCH == 'false') }}
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/Bilgaden"
          ref: "tinglysning"
          path: "${{ github.workspace }}/temp/"
          token: "${{ secrets.PAT }}"

      - name: Checkout Bilgaden repository (Tinglysning-temp-branch)
        if: ${{ env.EXIST_TINGLYSNING_TEMP_BRANCH == 'true' && env.EXIST_TINGLYSNING_BRANCH == 'true' }}
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/Bilgaden"
          ref: "tinglysning-temp"
          path: "${{ github.workspace }}/temp/"
          token: "${{ secrets.PAT }}"

      - name: Stitch BSON back together
        if: ${{ env.EXIST_TINGLYSNING_BRANCH == 'true' || env.EXIST_TINGLYSNING_TEMP_BRANCH == 'true' }}
        working-directory: "${{ github.workspace }}/temp/"
        run: |
          cat ${{ github.workspace }}/temp/*.part* > "${{ github.workspace }}/tinglysning.bson.gz"
          file "${{ github.workspace }}/tinglysning.bson.gz"
          
          rm -rf ${{ github.workspace }}/temp/

      - name: Checkout Bilgaden repository (Tinglysning-temp-branch)
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/Bilgaden"
          ref: "tinglysning-temp"
          path: "${{ github.workspace }}/temp/"
          sparse-checkout: |
            !/*
          sparse-checkout-cone-mode: false
          token: "${{ secrets.PAT }}"

      - name: Install MongoDB
        uses: ankane/setup-mongodb@v1
        with:
          mongodb-version: 8.0

      - name: Create MongoDB database
        if: ${{ env.EXIST_TINGLYSNING_BRANCH == 'false' && env.EXIST_TINGLYSNING_TEMP_BRANCH == 'false' }}
        run: |
          mongosh --host localhost:27017 <<EOF
            db = db.getSiblingDB('bilgaden');
            db.createCollection('tinglysning');
          EOF

      - name: Import BSON into MongoDB
        if: ${{ env.EXIST_TINGLYSNING_BRANCH == 'true' || env.EXIST_TINGLYSNING_TEMP_BRANCH == 'true' }}
        run: |
          mongorestore \
            --host localhost --port 27017 \
            --db bilgaden \
            --collection tinglysning \
            --maintainInsertionOrder \
            --gzip \
            "${{ github.workspace }}/tinglysning.bson.gz"
          
          rm -rf ${{ github.workspace }}/tinglysning.bson.gz

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install Go dependencies
        run: go mod tidy

      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps chromium

      - name: Run Tinglysning Go script
        run: |
          go run Tinglysning-GitHub.go
        env:
          REMOVE_COUNT_FROM_VINS: ${{ env.REMOVE_COUNT_FROM_VINS }}

      - name: Dump the entire database
        run: |
          mongodump \
            --host localhost --port 27017 \
            --db bilgaden \
            --collection=tinglysning \
            --gzip --out dump
          find ${{ github.workspace }}/dump/bilgaden -type f ! -name 'tinglysning.bson.gz' -delete

      - name: Split BSON-file into temp-directory
        run: |
          split -d -b ${{ inputs.github-upload-limit }}m ${{ github.workspace }}/dump/bilgaden/tinglysning.bson.gz ${{ github.workspace }}/temp/tinglysning.bson.gz.part
          
      - name: Upload BSON-file to GitHub Tinglysning-temp-branch
        working-directory: "${{ github.workspace }}/temp/"
        run: |
          git add --sparse .
          git commit -m "Uploaded tinglysning"
          git push

      - name: Rename Tinglysning-temp branch to Tinglysning and delete Tinglysning-temp branch  
        working-directory: "${{ github.workspace }}/temp/"
        run: |
          git fetch origin tinglysning-temp:tinglysning
          git push -u origin tinglysning --force

          git push origin --delete tinglysning-temp

      - name: Trigger next Runner
        if: ${{ env.SHOULD_SPAWN_NEW_RUNNER == 'true' }}
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'runner.yml',
              ref: 'main',
              inputs: {
                'remove-count-from-vins': '${{ env.REMOVE_COUNT_FROM_VINS }}',
                'github-upload-limit': '${{ inputs.github-upload-limit }}'
              }
            })
          github-token: ${{ secrets.PAT }}
    
      # - name: Archive BSON-file
      #   run: |
      #     mkdir -p ${{ github.workspace }}/tinglysning-zip
      #     zip -j -r -s ${{ inputs.discord-upload-limit }}m ${{ github.workspace }}/tinglysning-zip/tinglysning.bson.gz.zip ${{ github.workspace }}/dump/bilgaden

      # - name: Split BSON-file
      #   run: |
      #     mkdir -p ${{ github.workspace }}/tinglysning-split
      #     split -d -b ${{ inputs.discord-upload-limit }}m ${{ github.workspace }}/dump/bilgaden/tinglysning.bson.gz ${{ github.workspace }}/tinglysning-split/tinglysning.bson.gz.part

      # - name: Install Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.x'

      # - name: Install Python dependencies
      #   run: |
      #     pip install pymongo discord-webhook

      # - name: Upload BSON-file to GitHub Tinglysning-branch
      #   working-directory: "${{ github.workspace }}/temp/"
      #   run: |
      #     mv ${{ github.workspace }}/dump/bilgaden/tinglysning.bson.gz ${{ github.workspace }}/temp/tinglysning.bson.gz
      #     mv ${{ github.workspace }}/Branch-GitHub.py ${{ github.workspace }}/temp/Branch-GitHub.py
          
      #     python ${{ github.workspace }}/temp/Branch-GitHub.py tinglysning
      #   env:
      #     FILENAME: "tinglysning.bson.gz"
      #     FILENAME_NO_SUFFIX: "tinglysning"
      #     FILEPATH: "${{ github.workspace }}/temp/"
      #     BRANCHNAME: "tinglysning.zip"
      #     GITHUB_UPLOAD_LIMIT: "${{ inputs.github-upload-limit }}"

      # - name: Upload BSON-file to Discord
      #   run: |
      #     python ${{ github.workspace }}/UploadToDiscord-GitHub.py tinglysning
      #   env:
      #     FILENAME: "tinglysning.bson.gz"
